version: "3.8"

services:
  postgres:
    image: postgres:14
    stop_signal: SIGINT # Fast Shutdown mode
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "galv"
      POSTGRES_PORT: "5432"
    restart: unless-stopped
    # Add a volume if you want to persist data between runs
    # volumes:
    #   - .run/postgres_data:/var/lib/postgresql/data

  # Backend server uses mail service to send activation emails
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "8085:8025"
      - "1085:1025"

  backend:
    # For big development changes, best to target a specific SHA build rather than :latest in case backend changes.
    # If you prefer, of course, you can target a real backend deployment by changing the frontend GALV_API_BASE_URL
    image: ghcr.io/battery-intelligence-lab/galv-backend:latest
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "localhost"
      FRONTEND_VIRTUAL_HOST: "http://localhost:8002,https://localhost:8002"
      DJANGO_SETTINGS: "dev"
      DJANGO_SUPERUSER_PASSWORD: "admin"
    ports:
      - "8082:8000"
    depends_on:
      - postgres
      - mailhog
    volumes:
      - ./.schema:/spec

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_dev
    depends_on:
      - backend
    env_file:
      - .env.vite
    environment:
      GALV_API_BASE_URL: "http://localhost:8082"
      NODE_OPTIONS: "--max-old-space-size=32768"  # fix hanging container?
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./src:/app/src
    command: bash -c "(node _resource-check.js &) && pnpm start --host --port 80 -d"
  #    command: tail -F anything

  frontend_test:
    build:
      context: .
      dockerfile: Dockerfile_dev
    env_file:
      - .env.vite
    restart: "on-failure"
    command: "pnpm test"

  frontend_test_e2e:
    build:
      context: .
      dockerfile: Dockerfile_cypress
    env_file:
      - .env.vite
    restart: "on-failure"
    command: "pnpm cypress:e2e"

  frontend_build:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GALV_API_BASE_URL: "http://localhost:8082"
    env_file:
      - .env.vite
    restart: "no"
    command: "tail -F anything"