# fly.toml app configuration file generated for galv-frontend-dev on 2024-01-02T00:30:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "galv-frontend-dev"
primary_region = "lhr"

[env]
  VITE_GALV_API_BASE_URL = "https://galv-backend-dev.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
